development:
  dialect: mysql
  dir: db/migrations
  datasource: tosashimanto1:123456@tcp(127.0.0.1)/go_test001?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
  dialect: postgres
  dir: migrations/postgres
  datasource: dbname=myapp sslmode=disable
  table: migrations

